# Generated by Django 4.0 on 2022-02-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_system', '0002_alter_record_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byUsername', models.CharField(max_length=50)),
                ('month', models.PositiveSmallIntegerField()),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('rows', models.PositiveSmallIntegerField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
