# Generated by Django 4.0 on 2022-02-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_system', '0003_uploadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='upload_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
