# Generated by Django 4.0 on 2022-02-28 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_system', '0004_record_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='upload_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
