# Generated by Django 2.2.24 on 2022-04-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_system', '0006_accountparentlevele'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountparentlevele',
            name='allowChildProjections',
            field=models.BooleanField(default=False),
        ),
    ]
