# Generated by Django 4.0 on 2022-05-05 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_system', '0007_accountparentlevele_allowchildprojections'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('upload_id', models.UUIDField()),
                ('fund_type_parent_level_A', models.CharField(max_length=50)),
                ('fund_type_parent_level_B', models.CharField(max_length=50)),
                ('fund_type', models.CharField(max_length=50)),
                ('fund_source_parent_level_C', models.CharField(max_length=50)),
                ('fund_source_parent_level_D', models.CharField(max_length=50)),
                ('fund_source', models.CharField(max_length=50)),
                ('organization_parent_level_B', models.CharField(max_length=50)),
                ('organization_parent_level_C', models.CharField(max_length=50)),
                ('organization_parent_level_D', models.CharField(max_length=50)),
                ('organization_parent_level_E', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('account_parent_level_B', models.CharField(max_length=50)),
                ('account_parent_level_C', models.CharField(max_length=50)),
                ('account_parent_level_D', models.CharField(max_length=50)),
                ('account_parent_level_E', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('budget_amount', models.FloatField()),
                ('actual_YTD_beginning_of_period', models.FloatField()),
                ('period_net', models.FloatField()),
                ('actual_YTD_end_of_period', models.FloatField()),
                ('PO_Req_other_encumbrances', models.FloatField()),
                ('salary_encumbrance', models.FloatField()),
                ('remaining_budget', models.FloatField()),
                ('program', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadHistoryArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('byUsername', models.CharField(max_length=50)),
                ('month', models.PositiveSmallIntegerField()),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('rows', models.PositiveSmallIntegerField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
