# Generated by Django 4.0 on 2022-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_system', '0008_recordarchive_uploadhistoryarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalYear', models.PositiveSmallIntegerField()),
                ('byUsername', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rows', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='uploadhistoryarchive',
            name='deleted',
        ),
    ]
