# Generated by Django 2.2.24 on 2022-08-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_system', '0009_archivehistory_remove_uploadhistory_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountparentlevele',
            options={'verbose_name': 'Account Parent Level E Master', 'verbose_name_plural': 'Account Parent Level E Master Lists'},
        ),
    ]
