# Generated by Django 4.1.4 on 2023-09-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_upload_system", "0010_auto_20220818_0216"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountparentlevele",
            options={
                "permissions": [
                    ("can_enter_projection_amount", "Can Enter Projection Amount")
                ],
                "verbose_name": "Account Parent Level E Master",
                "verbose_name_plural": "Account Parent Level E Master Lists",
            },
        ),
    ]
