# Generated by Django 4.1.4 on 2023-09-19 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_upload_system", "0011_alter_accountparentlevele_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountparentlevele",
            options={
                "verbose_name": "Account Parent Level E Master",
                "verbose_name_plural": "Account Parent Level E Master Lists",
            },
        ),
    ]
