# Generated by Django 2.2.24 on 2022-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectionsupdatelog',
            name='fromValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projectionsupdatelog',
            name='toValue',
            field=models.FloatField(),
        ),
    ]
