# Generated by Django 2.2.24 on 2022-03-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0002_auto_20220324_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectionsupdatelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
