# Generated by Django 2.2.24 on 2022-03-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0004_auto_20220324_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectionsupdatelog',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_upload_system.Organization'),
        ),
    ]
