# Generated by Django 4.0 on 2022-03-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0002_projectionsupdatelog_time'),
        ('projections_update_system', '0006_currentprojections_comments'),
    ]

    operations = [
    ]
