# Generated by Django 2.2.24 on 2022-03-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0007_merge_20220327_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectionsupdatelog',
            name='time',
        ),
    ]
