# Generated by Django 2.2.24 on 2022-03-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0008_remove_projectionsupdatelog_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprojections',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
