# Generated by Django 4.0 on 2022-04-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0007_merge_20220327_2142'),
        ('projections_update_system', '0009_currentprojections_account'),
    ]

    operations = [
    ]
