# Generated by Django 2.2.24 on 2022-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0010_merge_20220401_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprojections',
            name='lastUpdatedFiscalMonth',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentprojections',
            name='lastUpdatedYear',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
