# Generated by Django 2.2.24 on 2022-04-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0011_auto_20220428_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentprojections',
            name='lastUpdatedFiscalMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentprojections',
            name='lastUpdatedYear',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
