# Generated by Django 2.2.24 on 2022-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0012_auto_20220428_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprojections',
            name='activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currentprojections',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currentprojections',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
