# Generated by Django 4.0 on 2022-05-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_system', '0009_archivehistory_remove_uploadhistory_deleted_and_more'),
        ('projections_update_system', '0013_auto_20220505_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionsUpdateLogArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byUserName', models.CharField(max_length=50)),
                ('fromValue', models.FloatField()),
                ('toValue', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_upload_system.accountparentlevele')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_upload_system.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
