# Generated by Django 2.2.24 on 2022-08-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0014_projectionsupdatelogarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewAccountToOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
