# Generated by Django 4.1.4 on 2023-03-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projections_update_system', '0015_addnewaccounttoorg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddNewAccountToOrg',
        ),
    ]
