# Generated by Django 2.2.24 on 2022-03-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_upload_system', '0005_alter_record_upload_id_alter_uploadhistory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizations', models.ManyToManyField(to='data_upload_system.Organization')),
            ],
        ),
    ]
