# Generated by Django 4.0 on 2022-04-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authorizeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizeduser',
            name='id',
        ),
        migrations.AlterField(
            model_name='authorizeduser',
            name='netId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
