# Generated by Django 4.0 on 2022-04-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_authorizeduser_id_alter_authorizeduser_netid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizedUser',
        ),
    ]
