# Generated by Django 2.2.24 on 2022-05-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_authorizeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedNetID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.CharField(max_length=20)),
            ],
        ),
    ]
