# Generated by Django 2.2.24 on 2022-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_authorizednetid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizednetid',
            name='id',
        ),
        migrations.AlterField(
            model_name='authorizednetid',
            name='netID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
